---
AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: '2.7.1'
  Exclude:
  - Gemfile
  - Rakefile
  - .rubocop.yml
  - attic/*
  - vendor/**/*
  - ./vendor/**/*
  - tmp/**/*
Metrics/MethodLength:
  Max: 20
  Exclude:
  - spec/**/*
Metrics/ClassLength:
  Max: 140
Metrics/PerceivedComplexity:
  Max: 10
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 20
Layout/LineLength:
  Description: People have wide screens, use them.
  Max: 200
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FormatString:
  Description: Prefer the % format format.
  EnforcedStyle: percent
Style/FormatStringToken:
  Description: Prefer the simpler template tokens over annotated ones.
  EnforcedStyle: template
Style/CommandLiteral:
  Description: use %()
  EnforcedStyle: percent_x
Style/RegexpLiteral:
  Description: use %r{}
  EnforcedStyle: percent_r
Style/PercentLiteralDelimiters:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/Documentation:
  Enabled: false
